name: Production Deployment

on:
  pull_request:
    branches:
      - master
jobs:
  deploy-and-test:
    name: Deploy to Staging and Test API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Railway CLI via npm
        run: npm install -g @railway/cli

      - name: Link Railway Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ secrets.RAILWAY_SERVICE_ID }}

      - name: Deploy to Railway Staging
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway up --ci --environment production

      - name: Wait for deployment
        run: sleep 30  
      
      - name: Get Staging Environment URL
        id: get-url
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          RAILWAY_URL=$(railway status --json | jq -r '.service.environments[] | select(.name=="staging").url')
          echo "Staging URL: $RAILWAY_URL"
          echo "::set-output name=staging_url::$RAILWAY_URL"

      - name: Test API Endpoints
        run: |
          echo "Testing API at ${{ steps.get-url.outputs.staging_url }}"
          curl -f ${{ steps.get-url.outputs.staging_url }}/api/health || exit 1
          curl -f ${{ steps.get-url.outputs.staging_url }}/api/users || exit 1
